# Build stage
FROM python:3.11-slim AS builder
WORKDIR /app
COPY app.py .
RUN pip install --no-cache-dir streamlit Pillow

# Final stage
FROM gcr.io/distroless/python3-debian12
EXPOSE 8501
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /app/app.py /app/app.py
WORKDIR /app
ENV PYTHONPATH=/usr/local/lib/python3.11/site-packages
CMD ["-m", "streamlit", "run", "app.py", "--server.address=0.0.0.0"]
